### ISSUE TITLE
Incorrect prerequisite

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/peterportal-client#236]
Was just using the site when I saw this. 

![image](https://user-images.githubusercontent.com/64875104/194231207-127f54df-3363-42dc-a5d0-8f5c15287cd1.png)

Note: ICS 45C and CSE 45C are the same course.

Looks like "prerequisite" is misspelled as well

**Comment by ethanwong16** [comment]
Nice catch @MinhxNguyen7 😎 , thanks for all your contributions!  I'll recreate this into separate issues for easier tracking.  In case you were curious, it looks like that prerequisite data might be outdated or from a previous year, since we should be getting this directly from WebSoc, but regardless we'll definitely need to update it!
