### ISSUE TITLE
Apostrophe decoding error with professor title

### ISSUE THREAD

**Issue by js0mmer** [icssc/peterportal-client#301]
Apostrophe appears as `&#039;` as seen in the image below.

![apostrophe](https://github.com/icssc/peterportal-client/assets/8922227/afe14b4d-be50-4207-8b3b-2ae421696d43)

**Comment by KevinWu098** [comment]
I believe this is on the PP-API side. Probably could clean it up on our end, but like [Minh mentioned here in AA](https://github.com/icssc/AntAlmanac/issues/464), not sure if it's idiomatic and/or expected behavior.

<img width="1728" alt="Screenshot 2023-07-29 at 3 08 26 AM" src="https://github.com/icssc/peterportal-client/assets/100006999/e31df573-cdc7-47cc-ad0b-16f6a1714918">

**Comment by js0mmer** [comment]
Seems to be a data inconsistency issue which should be fixed in PPAPI rewrite.
Example:
old:
![image](https://github.com/icssc/peterportal-client/assets/8922227/9ec50645-16db-4529-9cfd-89c5ea977ffd)

rewrite:
![image](https://github.com/icssc/peterportal-client/assets/8922227/247f46cd-5eea-4742-89bf-c5436d08b595)

Only some professors with an apostrophe in their title had this issue (certain Chancellor's Professors, Dean's Professors, etc.), most returned an apostrophe correctly.
