### ISSUE TITLE
Pagination Performance Improvement

### ISSUE THREAD

**Issue by aahei** [icssc/peterportal-client#310]
Currently, the new pagination feature requests all results from PPAPI, which might be inefficient, as there are around 6000 records for courses. PPAPI endpoint does not support range queries for now. Therefore, the temporary solution, before the feature is implemented, will be to request only the first few pages, and then request more only when users reach the end of the list.

**Comment by js0mmer** [comment]
I think this might be more related to websoc-fuzzy-search, given that we call that first on the frontend, get the list of courseIds, and request information for those specific courses from PPAPI through our backend.

**Comment by js0mmer** [comment]
Potential improvement: only get websoc-fuzzy-search results for a window of 3-5 pages at a time.
e.g. the current page + the 2 pages after it; for page 1 this would be the current page + 4 after, for page 2 + 3 after.
We only need enough data to be able to render the 5 page number buttons (and prev, next) in the pagination component appropriately

Limitting results speeds up response time of websoc-fuzzy-search greatly. The problem is, we can not specify offset for websoc-fuzzy-search. This means we would have to load all the results up to the current page plus the 2 after.

Being able to specify an offset may allow for faster response times but I'm not entirely sure since I don't know the implementation details. It may be just as slow as loading everything up to that page plus the 2 pages after so we should try that first.

**Comment by js0mmer** [comment]
search overhauled in #505
