### ISSUE TITLE
Add course mobile UI tweaks

### ISSUE THREAD

**Issue by js0mmer** [icssc/peterportal-client#324]
Currently if you go to add a course to the roadmap and cancel it on mobile, it looks like this.

![Recording 2023-06-01 at 23 18 10](https://github.com/icssc/peterportal-client/assets/8922227/30113302-3d62-4f18-9d27-51ec5a0a0757)

I think when the add course modal shows, it should confirm the name of the course with the user so they can make sure they select next one. i.e. instead of saying "Where do you want to add this course?" say "Where do you want to add AC ENG 20B?"

Also, I think the course search shouldn't close until the user clicks submit on the add course modal. That way if they click the wrong one, they can cancel and go right back to where they were in the search component.

**Comment by Awesome-E** [comment]
To be honest I think the whole flow of adding courses on mobile isn't the best.

I think it would make a lot more sense for there to be a plus button next to the schedule of each quarter, then when you click it you can search for classes. Each class in that list would then have a plus button or a trash can depending on whether it's in the list already or not – simply click that to change whether it's in the schedule.

This would be better for both of these (opposite) use cases:
1. Planning quarter by quarter – it would save a lot more clicks if you want to add 4 classes to the same quarter. It would be tap the plus on the quarter "schedule, search, click plus, search, click plus, (2 more times)" rather than "add courses, search, click, open year picker, pick year, open quarter picker, pick quarter, click submit, click add courses, search, click, open year picker, pick year, open quarter picker, pick quarter, click submit, (2 more times)"
2. Planning on a per-subject basis, where you plan a series of classes in a row across different quarters. It would be the same idea of "scroll to quarter, tap plus on schedule, search, tap the plus, (3 more times)", which is about the same amount of interaction required as currently.

https://github.com/icssc/peterportal-client/assets/54484616/f4e5e897-869f-459a-b4f7-ae3a6b320228
