### ISSUE TITLE
Missing Bio Sci 48

### ISSUE THREAD

**Issue by jamietevis** [icssc/peterportal-client#350]
When searching for classes to add Bio Sci 48 does not show up as an option.

**Comment by KevinWu098** [comment]
Can confirm that this is an issue. The searches `Bio Sci 46` and `Bio Sci 47` come up clean, 48 is just having an odd time

![](https://cdn.discordapp.com/attachments/910727722530123797/1146659496119246858/chrome-capture-2023-7-30_1.gif)

> Eddy (ecxyzzy) — Today at 9:17 PM
Hmm might be because they're using an older version of websoc-fuzzy-search
I'll address all of these issues in one big PR once we get the time changes moved in

Could possibly be solved by #344
